// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CollectConfig {
  url: string;
  name: string;
  desc: string | null;
  method: string;
  headers: any;
  body: string | null;
  map_rules: any;
  template_string: string;
  current_key: number | null;
  page_size_key: number | null;
  loop_request_by_pagination: boolean | null;
  cache_table_name: string | null;
}
