// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { CollectConfig } from "@/api/models/CollectConfig";

export interface CollectLog {
  id: number;
  collect_config_id: number | null;
  running_log: string | null;
  status: number;
  update_time: any;
  create_time: any;
  name: string;
  task_id: string | null;
}
