// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CollectConfig {
  id: number;
  url: string;
  name: string;
  desc: string | null;
  method: string;
  headers: any;
  body: string | null;
  map_rules: any;
  template_string: string;
  loop_request_by_pagination: boolean | null;
  max_number_of_result_data: number | null;
  filed_of_result_data: string | null;
  max_count_of_request: number | null;
  cache_table_name: string | null;
  db_columns_config: any;
  cron: string | null;
}
