// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface CollectLog {
  id: string;
  collect_config_id: number | null;
  running_log: string | null;
  status: number;
  update_time: any;
  create_time: any;
}
