// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DataSourceList {
  id: number;
  name?: string;
  database_name: string;
  table_schema?: string;
  database_type: string;
  host: string;
  port: string;
  user: string;
  password: string;
  del_flag: number;
  update_time: any;
  create_time: any;
}
