// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DataSharingConfig {
  id: number;
  api_id: string;
  name: string;
  query_sql: string;
  data_source: any;
  del_flag: number;
  update_time: any;
  create_time: any;
}
