// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DatasourceList { id: number, database_name: string, database_type: string, host: string, port: string, user: string, password: string, del_flag: number, update_time: any, create_time: any, }