// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SharingTaskInfoRes { list: Record<string, number>, num_items: bigint, rank_list: any, user_number: number, avg_num_user_calls_api: number, }