// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.


import { DataSharingConfig } from "@/api/models/DataSharingConfig";

export interface SharingRequestLog { log: string, data_sharing_config_id: number, data_sharing_config: DataSharingConfig; }