// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

import { SyncConfig } from "@/api/models/SyncConfig";

export interface SyncLog {
  id: string;
  running_log: string;
  status: number;
  sync_config_id: number;
  update_time: any;
  create_time: any;
  collect_config: SyncConfig;
}
