// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SyncConfig {
  id: number;
  name: string;
  data_source: any;
  source_table_name: string;
  query_sql: string;
  target_data_source: any;
  target_table_name: any;
  target_query_sql_template: any;
  cron: string | null;
  job_id: string | null;
}
