// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SystemInfo {
  total_memory: number;
  used_memory: number;
  total_swap: number;
  used_swap: number;
  cpu_uses: Array<number>;
  processes_cpu_usage: number | null;
  processes_disk_usage: any;
  processes_memory_usage: number | null;
}
