//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use schemars::JsonSchema;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, JsonSchema)]
#[sea_orm(table_name = "collect_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    pub url: String,
    pub method: String,
    pub headers: Option<Json>,
    pub body: Option<String>,
    pub map_rules: Option<Json>,
    pub template_string: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collect_log::Entity")]
    CollectLog,
}

impl Related<super::collect_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
