//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "collect_config")]
pub struct Model {
    pub url: String,
    pub method: String,
    pub headers: Option<Json>,
    pub body: Option<String>,
    pub map_rules: Option<Json>,
    pub template_string: String,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub current_key: Option<i32>,
    pub page_size_key: Option<i32>,
    pub loop_request_by_pagination: Option<bool>,
    pub cache_table_name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collect_log::Entity")]
    CollectLog,
}

impl Related<super::collect_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectLog.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
