//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, TS, Deserialize)]
#[sea_orm(table_name = "datasource_list")]
#[ts(
    export,
    export_to = "ui/api/models/auto-generates/DatasourceList.ts",
    rename = "DatasourceList"
)]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub database_name: String,
    pub database_type: String,
    pub host: String,
    pub port: String,
    pub user: String,
    pub password: String,
    pub del_flag: i32,
    #[ts(type = "any")]
    pub update_time: DateTime,
    #[ts(type = "any")]
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
