//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub mod prelude;

pub mod collect_config;
pub mod collect_log;
pub mod data_sharing_config;
pub mod data_source_list;
pub mod sharing_request_log;
pub mod sync_config;
pub mod sync_log;
// pub mod sync_log;
