//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use ts_rs::TS;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, TS, Default)]
#[sea_orm(table_name = "sharing_request_log")]
#[ts(
    export,
    export_to = "ui/api/models/auto-generates/SharingRequestLog.ts",
    rename = "SharingRequestLog"
)]
pub struct Model {
    #[sea_orm(primary_key)]
    #[serde(skip_deserializing)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub log: String,
    pub user_info: Option<String>,
    pub data_sharing_config_id: i32,
    #[serde(skip_deserializing)]
    pub update_time: DateTime,
    #[serde(skip_deserializing)]
    pub create_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::data_sharing_config::Entity",
        from = "Column::DataSharingConfigId",
        to = "super::data_sharing_config::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    DataSharingConfig,
}

impl Related<super::data_sharing_config::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DataSharingConfig.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
