//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "sync_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub data_source: String,
    pub source_table_name: String,
    pub query_sql: String,
    pub target_type: String,
    pub target_data_source: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
