// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SyncConfig { data_source: string, source_table_name: string, query_sql: string, target_type: string, target_data_source: string, }