name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --package data_process_center --bin data_process_center  --release --target x86_64-unknown-linux-gnu --verbose
    - name: Run tests
      run: cargo test --verbose
